### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by Brambor** [PyExplained/3D-Renderer#1]
Try to get rid of global variables.

If you use glob. vars across few functions, perhaps they should be a class?

Or maybe pass them as arguments if possible?

If you do that, it will be easier to see the code flow. This benefits you greatly as most time (even and especially your time!) is spend trying to understand the code already written.

**Comment by PyExplained** [comment]
Hi, 
Thanks for the tip! Because my GitHub-notifications didn't work for a while, I only just saw this (when I was about to upload a new version of the renderer with raytracing added). I'll see what I can do, but the new version still uses a lot of 'global' keywords. I also know that the code I wrote for the previous versions isn't very readable. When I wrote that code, I didn't care that much about readability yet (now I do). However, the code that I added to the new version has a lot more comments and I added a semi-detailed documentation 😉.

**Comment by Brambor** [comment]
Hi,
When you say
> However, the code that I added to the new version has a lot more comments
I got scared and immediately googled
https://blog.usejournal.com/stop-writing-code-comments-28fef5272752
However, it seems you are doing fine. If you haven't read about not writing comments yet, I still recommend reading it.

I seem to be in a mood to "fix (but nag actually)" your code. I will make an issue for small bits I feel like forcing onto you. It is nothing personal, I'm just trying to improve the overall coding community. Bear in mind, if I don't feel like rewriting my year old code, I haven't learned anything in the past year.

The issue is made! #2 

100% tip: get rid of the global variables!

Btw you can make versions with git, you don't have to put three folders in there named `version 1` `version 2` `version 3`.

**Comment by PyExplained** [comment]
If you like reading code, you are 100% allowed to read it and make issues whenever you want! I actually really appreciate that. But maybe try putting multiple together, so that I don't have 30 issues open so to speak. I got a quick read through the article and I definitely think that some of the names I give to my identifiers aren't that well-chosen... However, I won't stop using comments, because they make it way easier for me to find certain bits of codes and they can indicate what a certain block of code does when that block is too complex to see it immediately. 
Also, don't expect me to fix the issues soon. I wasn't really planning on still working that much on the renderer, but be sure to continue writing them if you'd like to. I'll also take a look at the version-thing (my GitHub-knowledge is still very limited).
