### ISSUE TITLE
Alarm - Virus & threat protection when download ZIP

### ISSUE THREAD

**Issue by jason990420** [PyExplained/3D-Renderer#4]
For URL: https://github.com/PyExplained/3D-Renderer

Code > Download ZIP

Got alram from Window security and failed to download.

![image](https://user-images.githubusercontent.com/55352169/163666717-b92d88c3-0bdb-48bb-87a6-14c967fb69c8.png)
![image](https://user-images.githubusercontent.com/55352169/163666762-b321e967-1cfd-43e7-a987-2dfd5e0cf7fa.png)

No this found when Download ZIP from others repository.

Platform: WIN10 + Google Chrome 100.0.4896.88

**Comment by PyExplained** [comment]
Hi jason990420, I just tested downloading the repository and indeed got the same error. It seems like there has been a Windows update that changed the virus scanning. I assume it thinks that I'm using a keylogger because there is code that listens for key inputs to be able to control the camera. But I can assure you that there isn't any malicious activity going on.
If you want to download the code, you should be able to do so by going to the settings and clicking on "allow on device" (this might be called differently, since my Windows is set to Dutch, but it should be similar).
Hope this helps

**Comment by jason990420** [comment]
How or where to go to the "allow on device" from settings window ? Not sure where to set the setting about "allow on device".

settings > ... > ... > allow device

**Comment by PyExplained** [comment]
I got there by downloading the code and clicking the notification that pops up (saying that there is a threat; this is the notification in your first screenshot). Then, under current threats, you should be able to click on the threat (the one you see in your second screenshot) and click on "allow" and "start action" (or something similar, I'm just guessing what the English translation would be because my PC is set to Dutch).
I hope this works for you. If not, don't hesitate to ask for more details.

**Comment by jason990420** [comment]
Yeah, got it downloded and thank you !
